### Create a new user
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "username": "ssdfgt",
    "password": "pas",
    "email": "sample.email@email.com"
}
### Get all users
GET http://localhost:3000/user

### Get a specific user with id of 1
GET http://localhost:3000/user/1
### Update a user with an id of 1
PUT http://localhost:3000/user/1?username=Finn&email=tyler.blevins@hotmail.com
### Delete a user with a specified id of 1
DELETE http://localhost:3000/user

### RENDER

### Create a new user
POST https://cse341w08project.onrender.com/user HTTP/1.1
content-type: application/json

{
    "username": "turnipHill1",
    "password": "$talberg2",
    "email": "sample.email@email.com"
}
### Get all users
GET https://cse341w08project.onrender.com/user

### Get a specific user with id of 1
GET https://cse341w08project.onrender.com/user/1